# Generated by Django 4.1.1 on 2022-10-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=200)),
                ('Office', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('startdate', models.DateField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
