# Generated by Django 4.1.1 on 2022-10-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('Email', models.EmailField(default=False, max_length=20)),
                ('country', models.CharField(choices=[('IN', 'INDIA'), ('USA', 'AMERICA'), ('RUS', 'RUSSIA'), ('AUSTR', 'AUSTRALIA')], default=None, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
